### ISSUE TITLE
why you use die?

### ISSUE THREAD

**Issue by IvanAlekseevichPopov** [yamilovs/SypexGeoBundle#3]
SypexGeoManager.php:56
Application сompletely stops work if file not available because you use die()

**Comment by yamilovs** [comment]
Hello! 
It's just a rudiment from original library - https://sypexgeo.net/files/SxGeo22_API.zip 
Im now working on refactoring this moment too.

**Comment by yamilovs** [comment]
Uh, finnaly.

This issue was resolved in raw sypex geo library that can be found here - https://github.com/yamilovs/SypexGeo

Bundle will be updated soon to 2nd version.
